In [10]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


df = pd.read_csv("Datasets/Advertising.csv")
feature_cols = ["TV", "radio", "newspaper"]

# Use the top 150 companies to train the Linear Regression Model
X_train = df[feature_cols][:150]
Y_train = df.sales[:150]

# TODO: Instansiate the model (Linear Regression) and train it

# TODO: Predict the botton 50 companies' sales

Step 1: create a scatter plot of features in dataset

In [11]:
# TODO: Instansiate the model (Linear Regression) and train it
lr_reg = LinearRegression()

lr_reg.fit(X_train, Y_train)

print(lr_reg.coef_)

print(lr_reg.intercept_)

[ 0.04700012  0.17993257 -0.00140273]
3.029766796293691


In [12]:
X_test = df[feature_cols][-50:]
Y_test = df.sales[-50:]

In [13]:
X_train.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [14]:
y_pred = lr_reg.predict(X_test)
y_pred
#predicting sales of bottom 50 companies

array([18.67186188, 10.15990172, 16.48950045, 18.17132726, 15.63964047,
        5.30168953, 15.19930681, 10.27021058, 10.15577653, 12.48190724,
       14.35100299, 13.43010832, 15.10545883, 17.32542469, 11.17561481,
       14.54411372, 10.60623457, 13.6578278 , 17.31920373, 18.29020846,
        7.44118029, 14.4553876 ,  7.54376735, 12.20415315, 14.07598825,
       24.7841683 , 20.11008458, 12.38328494, 16.41529992, 12.58762415,
       10.84616747, 14.23249384,  6.65512798, 24.18338541, 18.74887883,
       20.75225663,  9.92682913, 17.15002463, 18.96767352,  6.05302918,
       12.27336433,  8.51313117,  4.53156602, 18.42150484, 16.46286778,
        5.47156415,  8.32748549, 13.01318332, 23.82330766, 15.4737108 ])

In [15]:
lr_reg.score(X_test, Y_test)
#r_squared

0.8963519785440216

In [16]:
# or 
r2_score(Y_test, lr_reg.predict(X_test))

0.8963519785440216

In [17]:
#how much money could you predict if 100, 100, 20 values were spent by X company?
lr_reg.predict([[100,100,20]])

#or multiply line by line with the coef of the individual values of our model and add them

array([25.69498118])

In [18]:
#predict the values of the 152 company. Using the values from above we import the coef and intercept
#then multiply each element by each coef, and add the intercept.

In [ ]:
import numpy as np
df = pd.read_csv("Advertising.csv")
# the coefficient from linear regression model
W = np.array([0.04700012, 0.17993257, -0.00140273])
# the intercept from linear regression model
b = 3.0297667962936856